sonar.projectKey=python-fast-api-seeds
sonar.projectName=python-fast-api-seeds

sonar.sources=app
sonar.tests=tests

sonar.language=python
sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

# Optional: include only specific source dirs
# sonar.inclusions=app/**


# Optional: exclude virtual environments and other folders
sonar.exclusions=**/migrations/**, **/tests/**, **/__pycache__/**, **/*.pyc, **/venv/**, **/env/**

# Test and coverage settings (if using pytest and coverage)
# sonar.coverageReportPaths=coverage.xml
sonar.python.coverage.reportPaths=coverage-reports/coverage.xml
sonar.scanner.skipJreProvisioning=true

# sonar.host.url=https://qube.indexnine.com
# sonar.token=${SONAR_TOKEN}
