"""
Custom exceptions for the Research Agent System
"""
from app.common.exceptions.research_exceptions import (
    AIResearchAgentError,
    ArXivPaperError,
    BlogGenerationError,
    ConfigurationError,
    ContentGenerationError,
    DatabaseError,
    ExternalAPIError,
    InvalidArXivIdError,
    InvalidQueryError,
    LLMError,
    LLMQuotaExceededError,
    LLMRateLimitError,
    LLMResponseParseError,
    MissingAPIKeyError,
    MultiplePapersLimitError,
    NonAITopicError,
    PaperContentInsufficientError,
    PaperNotFoundError,
    PipelineError,
    QueryCategorizationError,
    RateLimitExceededError,
    RecordNotFoundError,
    ResearchDataInsufficientError,
    ResearchTimeoutError,
    ServiceUnavailableError,
    ShortformGenerationError,
    WorkflowStateError,
)

__all__ = [
    'AIResearchAgentError',
    'QueryCategorizationError',
    'InvalidQueryError',
    'NonAITopicError',
    'ResearchDataInsufficientError',
    'ResearchTimeoutError',
    'ContentGenerationError',
    'BlogGenerationError',
    'ShortformGenerationError',
    'ExternalAPIError',
    'RateLimitExceededError',
    'ServiceUnavailableError',
    'LLMError',
    'LLMResponseParseError',
    'LLMQuotaExceededError',
    'LLMRateLimitError',
    'PipelineError',
    'WorkflowStateError',
    'DatabaseError',
    'RecordNotFoundError',
    'ConfigurationError',
    'MissingAPIKeyError',
    'ArXivPaperError',
    'InvalidArXivIdError',
    'PaperNotFoundError',
    'PaperContentInsufficientError',
    'MultiplePapersLimitError',
]


